// WARNING!
//Do not edit this file.

import { BrowserRouter as Switch, Route, HashRouter } from 'react-router-dom';
import Landing from './components/Landing/Landing';
import PrivacyPolicy from './components/PrivacyPolicy';
import Termsofuse from './components/Termsofuse';

const App = () => {
  return (
    <Switch>
      <HashRouter>
        <Route exact path="/" component={Landing} />
      </HashRouter>
      <HashRouter>
        <Route exact path="/privacypolicy" component={PrivacyPolicy} />
      </HashRouter>
      <HashRouter>
        <Route exact path="/termsofuse" component={Termsofuse} />
      </HashRouter>
    </Switch>
  );
};

export default App;
